# Read the Docs configuration file for DLB
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - autotools-dev
    - autoconf
    - libtool
  jobs:
    pre_build:
    - ./bootstrap
    - ./configure
    post_build:
    - mkdir -p $READTHEDOCS_OUTPUT/html/ && mkdir -p $READTHEDOCS_OUTPUT/pdf/
    - rm -rf $READTHEDOCS_OUTPUT/html/* && rm -rf $READTHEDOCS_OUTPUT/pdf/*
    - make doxygen
    - make html
    - mv doc/user_guide/html/* $READTHEDOCS_OUTPUT/html
    - make pdf
    - mv doc/user_guide/pdf/DLBUserGuide.pdf $READTHEDOCS_OUTPUT/pdf

  #commands:
   # - ./bootstrap
   # - ./configure
   # 
   # - make doxygen
   # - make html
   # - mv doc/user_guide/html $READTHEDOCS_OUTPUT/html
   # - make pdf
   # - mv doc/user_guide/pdf $READTHEDOCS_OUTPUT/pdf


# Build documentation in the "docs/" directory with Sphinx
#sphinx:
#  configuration: doc/user_guide/source/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
# formats:
#    - pdf
#    - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
   install:
   - requirements: doc/user_guide/requirements.txt
